#!/bin/bash
# Path to root of CM project directory
CM_PROJECT_DIR=~/workspace/XenonHD
ANDROID_DEVICE=yuga

cd "$CM_PROJECT_DIR"

if [ -e "../../patches/build.name.cm14.diff" ]; then
  patch -R -p1 --no-backup-if-mismatch < ../../patches/build.name.cm14.diff
fi

#rm -rf .repo/local_manifests/xenonhd_manifest.xml

source build/envsetup.sh

#breakfast "$ANDROID_DEVICE"

repo sync --no-clone-bundle
#repo sync --force-sync --no-clone-bundle -c
