#!/bin/bash
# Path to root of CM project directory
CM_PROJECT_DIR=~/workspace/XenonHD
ANDROID_DEVICE=jfltexx

cd "$CM_PROJECT_DIR"

source build/envsetup.sh

if [ -e "../../patches/build.name.cm14.diff" ]; then
  patch -R -p1 --no-backup-if-mismatch < ../../patches/build.name.cm14.diff
fi

repo sync --no-clone-bundle
#repo sync --force-sync --no-clone-bundle -c

