#!/bin/bash
# Path to root of CM project directory
CM_PROJECT_DIR=~/workspace/XenonHD
# Set device
ANDROID_DEVICE=yuga
# Enable SU by default
export WITH_SU=true
# Add TWRP Recovery
#export WITH_TWRP=true
# Enable ccache
export USE_CCACHE=1
# Path to ccache dir
export CCACHE_DIR=~/workspace/XenonHD/.ccache
export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx80g"
## End Edit

cd "$CM_PROJECT_DIR"

prebuilts/misc/linux-x86/ccache/ccache -z
source build/envsetup.sh

make clean
breakfast "$ANDROID_DEVICE"
brunch "$ANDROID_DEVICE"
#mka recoveryimage

cd "$PROJECT_DIR" || exit
./prebuilts/sdk/tools/jack-admin kill-server

prebuilts/misc/linux-x86/ccache/ccache -s

echo ""
echo "Done."
echo ""
